# این ها از سکوهای مدل بودجه حمایت می شوند

github      :        #Replace با تا ۴ گیت هاب، نام کاربری که به عنوان مثال، [user1, user2]
patreon       :        شماره با یک نام کاربری پاترون
باز       :        شماره با یک نام کاربری مجموعه باز
کو_فی      :        شماره با یک نام کاربری کو-فی
tidelift       :        # جایگزین با یک تک فرم (نام) نام / بسته نام، به عنوان مثال، npm/babel
_بریج       :        # مکان با یک پروژه پل جامعه به نام مثال، ابر-فوندری
آزادی      :       شماره با یک نام کاربری لیبر
issuehunt      :       شماره با یک نام کاربری شماره شماره
otechie      :       شماره با یک نام کاربری
lfx_crowdfunding      :       # جایگزین با یک پروژه LFX کرود-فوند، به عنوان مثال، ابر-فوندی
سفارشی     :       #Replace با تا ۴ پشتیبانی سفارشی URLs e.g. [link1 , [link2]
